import type { Team, Fixture, Story, PlayerStat, WeeklyDigest } from '@/types'

// ── TEAMS ─────────────────────────────────────────────────────────────────────
export const TEAMS_SEED: Team[] = [
  // EPL
  { id:'MUN', name:'Manchester United', shortName:'Man United',   league:'EPL', colorPrimary:'#DA291C', colorSecondary:'#000000', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg', isUserSelected:true,  tier:'priority', isWildcard:false },
  { id:'ARS', name:'Arsenal',           shortName:'Arsenal',      league:'EPL', colorPrimary:'#EF0107', colorSecondary:'#FFFFFF', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg',                 isUserSelected:true,  tier:'priority', isWildcard:false },
  { id:'MCI', name:'Manchester City',   shortName:'Man City',     league:'EPL', colorPrimary:'#6CABDD', colorSecondary:'#1C2C5B', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg',    isUserSelected:true,  tier:'priority', isWildcard:false },
  { id:'LFC', name:'Liverpool',         shortName:'Liverpool',    league:'EPL', colorPrimary:'#C8102E', colorSecondary:'#F6EB61', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg',                isUserSelected:true,  tier:'priority', isWildcard:false },
  { id:'CFC', name:'Chelsea',           shortName:'Chelsea',      league:'EPL', colorPrimary:'#034694', colorSecondary:'#DBA111', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/c/cc/Chelsea_FC.svg',                  isUserSelected:true,  tier:'priority', isWildcard:false },
  { id:'TOT', name:'Tottenham Hotspur', shortName:'Spurs',        league:'EPL', colorPrimary:'#132257', colorSecondary:'#FFFFFF', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/b/b4/Tottenham_Hotspur.svg',           isUserSelected:true,  tier:'watch',    isWildcard:false },
  { id:'NEW', name:'Newcastle United',  shortName:'Newcastle',    league:'EPL', colorPrimary:'#241F20', colorSecondary:'#FFFFFF', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/5/56/Newcastle_United_Logo.svg',       isUserSelected:true,  tier:'underdog', isWildcard:false },
  { id:'FUL', name:'Fulham',            shortName:'Fulham',       league:'EPL', colorPrimary:'#CC0000', colorSecondary:'#000000', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/e/eb/Fulham_FC_%28shield%29.svg',      isUserSelected:true,  tier:'underdog', isWildcard:false },
  { id:'BRI', name:'Brighton',          shortName:'Brighton',     league:'EPL', colorPrimary:'#0057B8', colorSecondary:'#FFFFFF', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/f/fd/Brighton_%26_Hove_Albion_logo.svg',isUserSelected:true, tier:'underdog', isWildcard:false },
  { id:'BOU', name:'Bournemouth',       shortName:'Bournemouth',  league:'EPL', colorPrimary:'#DA291C', colorSecondary:'#000000', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/e/e5/AFC_Bournemouth_%282013%29.svg',  isUserSelected:true,  tier:'underdog', isWildcard:false },
  { id:'CRY', name:'Crystal Palace',    shortName:'Palace',       league:'EPL', colorPrimary:'#1B458F', colorSecondary:'#C4122E', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/a/a2/Crystal_Palace_FC_logo_%282022%29.svg',isUserSelected:true,tier:'watch',isWildcard:false },
  { id:'EVE', name:'Everton',           shortName:'Everton',      league:'EPL', colorPrimary:'#003399', colorSecondary:'#FFFFFF', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/7/7c/Everton_FC_logo.svg',              isUserSelected:false, tier:'watch',    isWildcard:false },
  { id:'AVL', name:'Aston Villa',       shortName:'Villa',        league:'EPL', colorPrimary:'#95BFE5', colorSecondary:'#670E36', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/9/9f/Aston_Villa_FC_crest_%282016%29.svg',isUserSelected:false,tier:'watch',  isWildcard:false },
  // La Liga
  { id:'BAR', name:'FC Barcelona',      shortName:'Barcelona',    league:'LA_LIGA', colorPrimary:'#A50044', colorSecondary:'#004D98', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg',   isUserSelected:true,  tier:'priority', isWildcard:false },
  { id:'RMA', name:'Real Madrid',       shortName:'Real Madrid',  league:'LA_LIGA', colorPrimary:'#FEBE10', colorSecondary:'#FFFFFF', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg',              isUserSelected:true,  tier:'priority', isWildcard:false },
  { id:'ATM', name:'Atlético Madrid',   shortName:'Atlético',     league:'LA_LIGA', colorPrimary:'#CE3524', colorSecondary:'#FFFFFF', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/f/f4/Atletico_Madrid_2017_logo.svg',   isUserSelected:true,  tier:'priority', isWildcard:false },
  { id:'VIL', name:'Villarreal',        shortName:'Villarreal',   league:'LA_LIGA', colorPrimary:'#FFD700', colorSecondary:'#009900', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/b/b9/Villarreal_CF_logo-en.svg',       isUserSelected:false, tier:'watch',    isWildcard:false },
  { id:'RBB', name:'Real Betis',        shortName:'Betis',        league:'LA_LIGA', colorPrimary:'#00954C', colorSecondary:'#FFFFFF', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/1/13/Real_betis_logo.svg',              isUserSelected:false, tier:'underdog', isWildcard:false },
  { id:'SEV', name:'Sevilla',           shortName:'Sevilla',      league:'LA_LIGA', colorPrimary:'#D2122E', colorSecondary:'#FFFFFF', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/3/3b/Sevilla_FC_logo.svg',              isUserSelected:false, tier:'watch',    isWildcard:false },
  // Bundesliga
  { id:'BMU', name:'Bayern Munich',     shortName:'Bayern',       league:'BUNDESLIGA', colorPrimary:'#DC052D', colorSecondary:'#0066B2', badgeUrl:'https://upload.wikimedia.org/wikipedia/commons/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282002%E2%80%932017%29.svg', isUserSelected:true, tier:'priority', isWildcard:false },
  { id:'BVB', name:'Borussia Dortmund', shortName:'Dortmund',     league:'BUNDESLIGA', colorPrimary:'#FDE100', colorSecondary:'#000000', badgeUrl:'https://upload.wikimedia.org/wikipedia/commons/6/67/Borussia_Dortmund_logo.svg',isUserSelected:true, tier:'watch',    isWildcard:false },
  { id:'LEV', name:'Bayer Leverkusen',  shortName:'Leverkusen',   league:'BUNDESLIGA', colorPrimary:'#E32221', colorSecondary:'#000000', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/5/59/Bayer_04_Leverkusen_logo.svg',  isUserSelected:true, tier:'priority', isWildcard:false },
  { id:'RBL', name:'RB Leipzig',        shortName:'Leipzig',      league:'BUNDESLIGA', colorPrimary:'#DD0741', colorSecondary:'#001E3C', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/0/04/RB_Leipzig_2014_logo.svg',       isUserSelected:false,tier:'watch',    isWildcard:false },
  { id:'SGE', name:'Eintracht Frankfurt',shortName:'Frankfurt',   league:'BUNDESLIGA', colorPrimary:'#E1000F', colorSecondary:'#000000', badgeUrl:'https://upload.wikimedia.org/wikipedia/commons/0/04/Eintracht_Frankfurt_Logo.svg',isUserSelected:false,tier:'watch',  isWildcard:false },
  // Serie A
  { id:'INT', name:'Inter Milan',       shortName:'Inter',        league:'SERIE_A', colorPrimary:'#0068A8', colorSecondary:'#000000', badgeUrl:'https://upload.wikimedia.org/wikipedia/commons/0/05/FC_Internazionale_Milano_2021.svg',isUserSelected:true, tier:'priority', isWildcard:false },
  { id:'ACM', name:'AC Milan',          shortName:'AC Milan',     league:'SERIE_A', colorPrimary:'#FB090B', colorSecondary:'#000000', badgeUrl:'https://upload.wikimedia.org/wikipedia/commons/d/d0/Logo_of_AC_Milan.svg',           isUserSelected:true, tier:'priority', isWildcard:false },
  { id:'JUV', name:'Juventus',          shortName:'Juventus',     league:'SERIE_A', colorPrimary:'#000000', colorSecondary:'#FFFFFF', badgeUrl:'https://upload.wikimedia.org/wikipedia/commons/1/15/Juventus_FC_2017_icon_%28black%29.svg',isUserSelected:true,tier:'watch',isWildcard:false },
  { id:'NAP', name:'Napoli',            shortName:'Napoli',       league:'SERIE_A', colorPrimary:'#12A0C7', colorSecondary:'#FFFFFF', badgeUrl:'https://upload.wikimedia.org/wikipedia/commons/2/2d/SSC_Napoli_%282021%29.svg',      isUserSelected:false,tier:'watch',   isWildcard:false },
  { id:'ATA', name:'Atalanta',          shortName:'Atalanta',     league:'SERIE_A', colorPrimary:'#1E4E8C', colorSecondary:'#000000', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/8/84/Atalanta_BC_logo.svg',               isUserSelected:false,tier:'underdog',isWildcard:false },
  // Ligue 1
  { id:'PSG', name:'Paris Saint-Germain',shortName:'PSG',         league:'LIGUE_1', colorPrimary:'#004170', colorSecondary:'#DA291C', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/a/a7/Paris_Saint-Germain_F.C..svg',       isUserSelected:true, tier:'priority', isWildcard:false },
  { id:'ASM', name:'AS Monaco',         shortName:'Monaco',       league:'LIGUE_1', colorPrimary:'#CE1126', colorSecondary:'#FFFFFF', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/7/76/AS_Monaco_FC.svg',                   isUserSelected:true, tier:'underdog', isWildcard:true  },
  { id:'OLM', name:'Marseille',         shortName:'Marseille',    league:'LIGUE_1', colorPrimary:'#2FAEE0', colorSecondary:'#FFFFFF', badgeUrl:'https://upload.wikimedia.org/wikipedia/commons/d/d8/Olympique_Marseille_logo.svg',   isUserSelected:false,tier:'watch',   isWildcard:false },
  { id:'LIL', name:'Lille',             shortName:'Lille',        league:'LIGUE_1', colorPrimary:'#DA291C', colorSecondary:'#000000', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/d/d7/LOSC_Lille_logo.svg',                 isUserSelected:false,tier:'watch',   isWildcard:false },
  // UCL-only
  { id:'GAL', name:'Galatasaray',       shortName:'Galatasaray',  league:'UCL' as any, colorPrimary:'#DC143C', colorSecondary:'#FFD700', badgeUrl:'https://upload.wikimedia.org/wikipedia/commons/4/42/Galatasaray_Sports_Club_Logo.png',isUserSelected:false,tier:'watch',isWildcard:false },
  { id:'BOG', name:'Bodø/Glimt',       shortName:'Bodo/Glimt',   league:'UCL' as any, colorPrimary:'#FFD700', colorSecondary:'#000000', badgeUrl:'https://upload.wikimedia.org/wikipedia/en/a/a6/FK_Bod%C3%B8%2FGlimt_logo.svg',    isUserSelected:false,tier:'underdog',isWildcard:false },
]

// ── FIXTURES ──────────────────────────────────────────────────────────────────
export const FIXTURES_SEED: (Omit<Fixture, 'matchDate'> & { matchDate: string })[] = [
  {
    id: 'ATH-BAR-2026-03-07',
    homeTeamId: 'ATH', awayTeamId: 'BAR',
    homeName: 'Athletic Club', awayName: 'Barcelona',
    homeColorPrimary: '#EE2523', homeColorSecondary: '#FFFFFF',
    awayColorPrimary: '#A50044', awayColorSecondary: '#004D98',
    competition: 'La Liga', league: 'LA_LIGA',
    matchDate: '2026-03-07T20:00:00+01:00',
    status: 'scheduled',
    tier: 'priority',
    winProbHome: 20.1, winProbAway: 57.9, winProbDraw: 22.0,
    preview: `Hansi Flick's Barcelona machine rolls into the Basque cauldron of San Mamés — one of European football's great atmospheric tests — the night before their UCL knockout campaign truly ignites. Flick faces the classic manager's dilemma that has humbled tacticians throughout the game's history: rotate and risk a slip in La Liga's tightest title race in years, or field the first eleven and arrive at St James' Park on Tuesday with legs that have already run 90 minutes of war?\n\nLewandowski, Yamal, and Raphinha are all in contention. Frenkie de Jong, absent through injury, remains the conspicuous gap in the engine room. Athletic Bilbao in their own stadium are not the same club that folds politely on the road — San Mamés has swallowed better visitors than this, and their fans will arrive tonight with the noise and the fury of people who understand that European nights begin at home.\n\nBarcelona lead La Liga with 65 points from 27 games. Every point matters. Yet Flick knows that UCL knockout football — the reason this squad was assembled in the first place — is the real exam. Tonight is the warm-up act. Tuesday is the theatre.`,
    refereeName: 'José María Sánchez Martínez',
    refereeNote: 'Experienced La Liga official. Averages 4.1 yellow cards per game. Controls intensity without over-officiating.',
    isDerby: false, isPinned: false, weekLabel: 'mar-7-2026',
  },
  {
    id: 'NEW-BAR-2026-03-10',
    homeTeamId: 'NEW', awayTeamId: 'BAR',
    homeName: 'Newcastle', awayName: 'Barcelona',
    homeColorPrimary: '#241F20', homeColorSecondary: '#FFFFFF',
    awayColorPrimary: '#A50044', awayColorSecondary: '#004D98',
    competition: 'UCL R16 Leg 1', league: 'UCL',
    matchDate: '2026-03-10T20:00:00+00:00',
    status: 'scheduled',
    tier: 'unmissable',
    winProbHome: 33.7, winProbAway: 41.3, winProbDraw: 25.0,
    preview: `St James' Park. Fifty-two thousand voices against the greatest club machine currently operating in world football. This is what the Champions League was invented for — not the comfortable group stage nights against predictable opposition, but this: the underdog who earned their place against the aristocrat who expected no resistance.\n\nEddie Howe's Newcastle arrive at this fixture wounded. Bruno Guimarães, their midfield conductor and heartbeat, is absent. Fabian Schär, Lewis Miley, Tino Livramento, and Emil Krafth — all sidelined. This is a squad held together with athletic tape, collective will, and the specific kind of stubbornness that only comes from a fanbase that has been waiting decades for a night like this. In September, these same sides met in the UCL league phase at this very ground. Barça won 2-1. The scoreline flattered nobody.\n\nAnd now there is Marcus Rashford — sold by Manchester United to Barcelona in January, who scored against Newcastle in the UCL league phase. He returns to England not as the prodigal son but as the visiting threat. Frenkie de Jong is absent for Barça, reducing their midfield range. Newcastle have nothing to lose, which makes them the most dangerous team on the continent tonight.`,
    refereeName: 'Daniele Orsato',
    refereeNote: 'Italy\'s most decorated referee. UCL specialist, has taken finals. Known for letting the game flow and protecting tempo.',
    isDerby: false, isPinned: true, weekLabel: 'mar-7-2026',
  },
  {
    id: 'GAL-LFC-2026-03-10',
    homeTeamId: 'GAL', awayTeamId: 'LFC',
    homeName: 'Galatasaray', awayName: 'Liverpool',
    homeColorPrimary: '#DC143C', homeColorSecondary: '#FFD700',
    awayColorPrimary: '#C8102E', awayColorSecondary: '#F6EB61',
    competition: 'UCL R16 Leg 1', league: 'UCL',
    matchDate: '2026-03-10T17:45:00+00:00',
    status: 'scheduled',
    tier: 'watch',
    winProbHome: 23.2, winProbAway: 53.3, winProbDraw: 23.5,
    preview: `The Ali Sami Yen Stadium in Istanbul has swallowed better visitors than this. Liverpool know European nights in Turkish cauldrons — they lived through Istanbul 2005, though that particular night ended rather differently to how it began. Galatasaray's stadium is smoke and noise and raw collective fury, the kind of atmosphere that turns good teams into hesitant ones and nervous teams into ruins.\n\nLiverpool stumbled to a 2-1 defeat to Wolves in their last Premier League outing, a wobble that has left them sixth on 48 points — a position that feels inconsistent with the quality Arne Slot has assembled. The UCL knockout is both a release valve and a character test. Great teams historically find their best selves when the tournament format demands it.\n\nThe Reds are 53.3% favourites. That feels accurate and simultaneously irrelevant — percentages do not account for flares, crowd noise, or the specific psychological weight of being an away team in Turkey.`,
    refereeName: 'Slavko Vinčić',
    refereeNote: 'Slovenian. One of UEFA\'s rising officials. Tends to book early, which can defuse or inflame atmospheres depending on the temperament of the home side.',
    isDerby: false, isPinned: false, weekLabel: 'mar-7-2026',
  },
  {
    id: 'ATM-TOT-2026-03-10',
    homeTeamId: 'ATM', awayTeamId: 'TOT',
    homeName: 'Atlético Madrid', awayName: 'Spurs',
    homeColorPrimary: '#CE3524', homeColorSecondary: '#FFFFFF',
    awayColorPrimary: '#132257', awayColorSecondary: '#FFFFFF',
    competition: 'UCL R16 Leg 1', league: 'UCL',
    matchDate: '2026-03-10T20:00:00+00:00',
    status: 'scheduled',
    tier: 'watch',
    winProbHome: 61.8, winProbAway: 16.6, winProbDraw: 21.6,
    preview: `Diego Simeone's trap is set at the Metropolitano. Atlético Madrid — 54 points and third in La Liga, UCL knockout regulars under the Argentine — know exactly what they are doing in fixtures like this one. They slow the game down. They make the opponent feel the clock. They defend with the kind of organised paranoia that drives technical teams to distraction.\n\nSpurs arrive at this fixture in historically poor form: 16th in the Premier League on 29 points, beaten 3-1 by Crystal Palace last week, 11 European nights into a season where they have been found out repeatedly for the same structural weaknesses. And yet. European knockout football is its own dimension.\n\nIf Atlético progress, a quarter-final against Barcelona awaits — a mini-Clásico of fierce rivalry. Simeone knows this. It motivates him more than any wage packet.`,
    refereeName: 'Sandro Schärer',
    refereeNote: 'Swiss. Composed in big occasions. Respects physicality and allows the game to breathe. Good for a Simeone side.',
    isDerby: false, isPinned: false, weekLabel: 'mar-7-2026',
  },
  {
    id: 'ATA-BMU-2026-03-10',
    homeTeamId: 'ATA', awayTeamId: 'BMU',
    homeName: 'Atalanta', awayName: 'Bayern Munich',
    homeColorPrimary: '#1E4E8C', homeColorSecondary: '#000000',
    awayColorPrimary: '#DC052D', awayColorSecondary: '#0066B2',
    competition: 'UCL R16 Leg 1', league: 'UCL',
    matchDate: '2026-03-10T20:00:00+00:00',
    status: 'scheduled',
    tier: 'watch',
    winProbHome: 20.2, winProbAway: 59.0, winProbDraw: 20.8,
    preview: `Gian Piero Gasperini's Atalanta dismantled Borussia Dortmund 4-1 in the UCL playoff round — the kind of scoreline that reframes what a club is capable of and what the competition's field actually looks like. Bayern are 59% favourites on paper. Paper does not play at the Gewiss Stadium.\n\nHarry Kane continues to be Germany's most reliable import. He has scored consistently in the Bundesliga and his partnership with Leroy Sané has matured into something genuinely threatening. But Gasperini's press, his rotations, his willingness to sacrifice conventional shape for positional chaos — these are things Bayern's back line has not encountered this season.\n\nThis is the tactical chess match of the round for those who study the game. Both managers will claim to have scouted every weakness. Only 90 minutes will confirm who was right.`,
    refereeName: 'Anthony Taylor',
    refereeNote: 'English referee on UEFA duty. VAR-comfortable. Handled multiple EPL heavyweights this season.',
    isDerby: false, isPinned: false, weekLabel: 'mar-7-2026',
  },
  {
    id: 'LEV-ARS-2026-03-11',
    homeTeamId: 'LEV', awayTeamId: 'ARS',
    homeName: 'Bayer Leverkusen', awayName: 'Arsenal',
    homeColorPrimary: '#E32221', homeColorSecondary: '#000000',
    awayColorPrimary: '#EF0107', awayColorSecondary: '#FFFFFF',
    competition: 'UCL R16 Leg 1', league: 'UCL',
    matchDate: '2026-03-11T17:45:00+00:00',
    status: 'scheduled',
    tier: 'unmissable',
    winProbHome: 15.8, winProbAway: 62.3, winProbDraw: 21.9,
    preview: `Arsenal — FIRST in the Premier League with 67 points, 20 wins, 3 defeats — march into the BayArena with the quiet but unmistakable confidence of a team that believes their time has arrived. Mikel Arteta's transformation of this club from perennial nearly-men into organised, relentless, technically elite contenders is the greatest managerial evolution in English football since Ferguson's final years.\n\nLeverkusen under Xabi Alonso are formidable, intelligent, and built for moments exactly like this one. But Arsenal's 62.3% win probability is not an accident of mathematics — it reflects real and current dominance. The high press, counter-press, Saka-Martinelli width, and Havertz's intelligent dropping to link play creates overloads that opposition teams simply cannot solve for 90 minutes.\n\nThe thing nobody is saying enough: if Arsenal win this tie and progress through the UCL quarter-finals, they are playing for a treble. The league, the FA Cup, and the Champions League are all live simultaneously. This is the fixture where their season either expands into history or contracts back into ambition.`,
    refereeName: 'François Letexier',
    refereeNote: 'France\'s finest. One of Europe\'s fastest-rising officials. Technically precise, allows pace, does not over-manage. Perfect for this type of fixture.',
    isDerby: false, isPinned: true, weekLabel: 'mar-7-2026',
  },
  {
    id: 'RMA-MCI-2026-03-11',
    homeTeamId: 'RMA', awayTeamId: 'MCI',
    homeName: 'Real Madrid', awayName: 'Man City',
    homeColorPrimary: '#FEBE10', homeColorSecondary: '#FFFFFF',
    awayColorPrimary: '#6CABDD', awayColorSecondary: '#1C2C5B',
    competition: 'UCL R16 Leg 1', league: 'UCL',
    matchDate: '2026-03-11T20:00:00+00:00',
    status: 'scheduled',
    tier: 'unmissable',
    winProbHome: 28.0, winProbAway: 47.0, winProbDraw: 25.0,
    preview: `The Bernabéu. The fixture of this entire round, this entire season, possibly this entire decade. Real Madrid — who absorbed a shocking home loss to Getafe before recovering to beat Celta Vigo 2-1 — host a Manchester City side that Pep Guardiola has refined into European football's most mechanically complete project. Erling Haaland is the most feared striker on the planet. Mbappé carries a knee concern that has clouded Madrid's preparation.\n\nCity's 47% win probability makes them slight favourites — a reflection of their squad depth, their tactical flexibility, and Haaland's relentless goal production. But the Bernabéu is not a neutral venue. It has its own gravitational pull, its own supernatural claim on the Champions League. The stadium has watched this competition bend towards Madrid in ways that cannot be explained by xG models or pressing intensity. It is a place where late goals arrive as if scripted, where comebacks materialise from tactical chaos, where the impossible presents itself as routine.\n\nThis is the third act of a trilogy. City won in 2023 to claim their first European crown. Madrid ended their run in 2024. What follows tonight will be written about for years.`,
    refereeName: 'Clément Turpin',
    refereeNote: 'France. Has taken UCL finals. One of UEFA\'s three most trusted officials. Controls the temperature without strangling the game.',
    isDerby: false, isPinned: true, weekLabel: 'mar-7-2026',
  },
  {
    id: 'PSG-CFC-2026-03-11',
    homeTeamId: 'PSG', awayTeamId: 'CFC',
    homeName: 'PSG', awayName: 'Chelsea',
    homeColorPrimary: '#004170', homeColorSecondary: '#DA291C',
    awayColorPrimary: '#034694', awayColorSecondary: '#DBA111',
    competition: 'UCL R16 Leg 1', league: 'UCL',
    matchDate: '2026-03-11T20:00:00+00:00',
    status: 'scheduled',
    tier: 'watch',
    winProbHome: 51.6, winProbAway: 24.1, winProbDraw: 24.3,
    preview: `Post-Mbappé PSG are a different proposition. Kvaratskhelia — signed from Napoli with the specific brief of replacing genius with genius — has been excellent in Ligue 1 but remains untested in knockout Europe at the highest level. The Parc des Princes in a European night still generates atmosphere, still carries weight, still intimidates.\n\nChelsea demolished Aston Villa 4-1 in their most recent outing — their best performance of the season by margin, not just result. They arrive in Paris in form, with belief, and with the specific advantage of being underestimated. PSG at 51.6% to win reflects uncertainty, not dominance.\n\nChelsea's UCL run would reshape their entire season narrative. Fifth in the Premier League, hovering between Champions League qualification and Europa League consolation, a deep European run changes the story completely.`,
    refereeName: 'István Kovács',
    refereeNote: 'Romanian. Technically solid. Averaged 3.8 yellow cards per UCL match this season. Fair but firm.',
    isDerby: false, isPinned: false, weekLabel: 'mar-7-2026',
  },
  {
    id: 'ACM-INT-2026-03-08',
    homeTeamId: 'ACM', awayTeamId: 'INT',
    homeName: 'AC Milan', awayName: 'Inter Milan',
    homeColorPrimary: '#FB090B', homeColorSecondary: '#000000',
    awayColorPrimary: '#0068A8', awayColorSecondary: '#000000',
    competition: 'Serie A — Derby della Madonnina', league: 'SERIE_A',
    matchDate: '2026-03-08T19:45:00+00:00',
    status: 'scheduled',
    tier: 'watch',
    winProbHome: 27.6, winProbAway: 42.3, winProbDraw: 30.1,
    preview: `The Derby della Madonnina. Somewhere in Milan's bones, this fixture has existed long enough to become part of the city's architecture — as permanent as the Duomo, as contentious as the traffic. AC Milan and Inter share San Siro, share a city, and share absolutely nothing else.\n\nMilan won 2-0 at Cremonese last week and arrive with momentum. Inter, humiliatingly eliminated from the UCL league phase by Bodø/Glimt — the Norwegian club with a budget smaller than Milan's wage bill for one player — carry a chip that could fuel them or distract them. Inter's 42.3% win probability reflects their underlying quality, not their current mood.\n\nIn Serie A derbies, the table means less than the last derby result. And the last time these sides met, the result still stings for one set of supporters. That is all either team will be thinking about when the referee's whistle sounds at San Siro.`,
    refereeName: 'Maurizio Mariani',
    refereeNote: 'Serie A specialist. Keeps composure in derby intensity. Has managed this fixture three times previously without major controversy.',
    isDerby: true, isPinned: false, weekLabel: 'mar-7-2026',
  },
  {
    id: 'ARS-EVE-2026-03-14',
    homeTeamId: 'ARS', awayTeamId: 'EVE',
    homeName: 'Arsenal', awayName: 'Everton',
    homeColorPrimary: '#EF0107', homeColorSecondary: '#FFFFFF',
    awayColorPrimary: '#003399', awayColorSecondary: '#FFFFFF',
    competition: 'Premier League', league: 'EPL',
    matchDate: '2026-03-14T17:30:00+00:00',
    status: 'scheduled',
    tier: 'watch',
    winProbHome: 73.5, winProbAway: 9.2, winProbDraw: 17.3,
    preview: `Arsenal at the Emirates between UCL legs. Arteta will not rotate carelessly — the Leverkusen second leg is three days away — but he also cannot afford a dropped point in a title race where Man City are seven behind and counting. Everton are eighth on 43 points, respectable, organised under their manager, and unlikely to come to north London looking for anything other than a point.\n\nArsenal's 73.5% win probability is the market's way of saying: this is a game Arsenal should win, and probably will, and anything less would be genuinely surprising given the gap in squad quality.\n\nWatch the team selection. If Arteta rests Saka, it tells you everything about his UCL priorities.`,
    refereeName: 'Michael Oliver',
    refereeNote: 'England\'s most consistent referee. Controlled, reads the game well, performs under pressure.',
    isDerby: false, isPinned: false, weekLabel: 'mar-7-2026',
  },
  {
    id: 'CFC-NEW-2026-03-14',
    homeTeamId: 'CFC', awayTeamId: 'NEW',
    homeName: 'Chelsea', awayName: 'Newcastle',
    homeColorPrimary: '#034694', homeColorSecondary: '#DBA111',
    awayColorPrimary: '#241F20', awayColorSecondary: '#FFFFFF',
    competition: 'Premier League', league: 'EPL',
    matchDate: '2026-03-14T17:30:00+00:00',
    status: 'scheduled',
    tier: 'watch',
    winProbHome: 53.4, winProbAway: 23.9, winProbDraw: 22.7,
    preview: `Chelsea host Newcastle between the Magpies' two Champions League legs against Barcelona. Eddie Howe's squad — injury-ravaged, missing Bruno Guimarães and four other regulars — play PSG on Wednesday, then must turn around immediately for this, then face the Camp Nou on the following Wednesday. The scheduling is ruthless.\n\nChelsea are in form. Their 4-1 win over Aston Villa is the kind of performance that signals a team in its best rhythm. 53.4% to win. Newcastle may be distracted, may rotate, may be playing for next Wednesday already. That is the UCL's hidden tax on smaller squads in Europe.`,
    refereeName: 'Stuart Attwell',
    refereeNote: 'EPL regular. Known for VAR consultation. Technically proficient.',
    isDerby: false, isPinned: false, weekLabel: 'mar-7-2026',
  },
  {
    id: 'MUN-AVL-2026-03-15',
    homeTeamId: 'MUN', awayTeamId: 'AVL',
    homeName: 'Man United', awayName: 'Aston Villa',
    homeColorPrimary: '#DA291C', homeColorSecondary: '#000000',
    awayColorPrimary: '#95BFE5', awayColorSecondary: '#670E36',
    competition: 'Premier League', league: 'EPL',
    matchDate: '2026-03-15T14:00:00+00:00',
    status: 'scheduled',
    tier: 'priority',
    winProbHome: 54.3, winProbAway: 22.2, winProbDraw: 23.5,
    preview: `Old Trafford. Michael Carrick's United had built an unbeaten Premier League run of eleven games — the kind of run that makes supporters remember what this club is supposed to feel like — before it was ended by Newcastle's 2-1 win last week. Bruno Fernandes and Benjamin Sesko both scored in the previous home win against Crystal Palace. The partnership between them is this United side's most reliable weapon.\n\nMason Mount is nearing return. Lisandro Martínez and Matthijs de Ligt remain absent. Harry Maguire and Luke Shaw both missed the Newcastle game through illness — their availability this weekend is the defining question of Carrick's selection.\n\nUnited are third on 51 points. Aston Villa sit fourth on the same 51 points. This is a six-pointer in the truest sense — the top four battle in real time, at Old Trafford, with a partisan crowd who know exactly what is at stake. Carrick's side are 54.3% favourites. The Theatre of Dreams needs a statement.`,
    refereeName: 'Chris Kavanagh',
    refereeNote: 'EPL. Experienced with high-stakes matches. VAR-comfortable. Tends toward leniency in physical duels.',
    isDerby: false, isPinned: true, weekLabel: 'mar-7-2026',
  },
  {
    id: 'LFC-TOT-2026-03-15',
    homeTeamId: 'LFC', awayTeamId: 'TOT',
    homeName: 'Liverpool', awayName: 'Spurs',
    homeColorPrimary: '#C8102E', homeColorSecondary: '#F6EB61',
    awayColorPrimary: '#132257', awayColorSecondary: '#FFFFFF',
    competition: 'Premier League', league: 'EPL',
    matchDate: '2026-03-15T16:30:00+00:00',
    status: 'scheduled',
    tier: 'watch',
    winProbHome: 72.0, winProbAway: 11.6, winProbDraw: 16.4,
    preview: `Anfield. Liverpool 72% to win against a Tottenham side currently sixteenth in the Premier League, which is a sentence that would have seemed implausible twelve months ago. Spurs have lost their last four league games. Liverpool are inconsistent — that Wolves defeat still lingers — but Anfield's home advantage is one of football's genuine differentiators.\n\nBoth clubs have UCL knockout commitments this week. For Liverpool, Istanbul Tuesday and Anfield Sunday creates a rhythm question. For Spurs, the Atletico second leg follows this. Rotation is inevitable. The question is whether either manager rotates enough to change the outcome significantly.\n\nLiverpool need the win to stay in the top-four conversation. Spurs need the win to not be in the relegation conversation. Different urgencies, same three points.`,
    refereeName: 'Anthony Taylor',
    refereeNote: 'Has managed Anfield many times. Confident in the environment.',
    isDerby: false, isPinned: false, weekLabel: 'mar-7-2026',
  },
  {
    id: 'MCI-RMA-2026-03-17',
    homeTeamId: 'MCI', awayTeamId: 'RMA',
    homeName: 'Man City', awayName: 'Real Madrid',
    homeColorPrimary: '#6CABDD', homeColorSecondary: '#1C2C5B',
    awayColorPrimary: '#FEBE10', awayColorSecondary: '#FFFFFF',
    competition: 'UCL R16 Leg 2', league: 'UCL',
    matchDate: '2026-03-17T20:00:00+00:00',
    status: 'scheduled',
    tier: 'unmissable',
    winProbHome: 47.0, winProbAway: 28.0, winProbDraw: 25.0,
    preview: `The Etihad. Return leg. City at home, the Bernabéu's supernatural pull temporarily suspended, the crowd behind Haaland rather than against him. If Real Madrid took a lead in the first leg, this becomes a City siege. If City lead, Madrid must do in Manchester what they do in the Bernabéu — find something that cannot be explained by data.\n\nGuardiola's tactical genius is most visible not in comfortable wins but in high-pressure knockout situations where the margin for error is a single moment. He has lost UCL semi-finals at the last step. He will not have forgotten. This City squad might be his last great chance to win Europe again before this particular cycle ends.\n\nKhvicha Kvaratskhelia — no, wrong team. This is City versus Madrid. Haaland versus whoever Madrid assign to shadow him. The third act of the trilogy.`,
    refereeName: 'Clément Turpin',
    refereeNote: 'Same as Leg 1. UEFA prefers consistency in officiating across both legs.',
    isDerby: false, isPinned: true, weekLabel: 'mar-7-2026',
  },
  {
    id: 'BAR-NEW-2026-03-18',
    homeTeamId: 'BAR', awayTeamId: 'NEW',
    homeName: 'Barcelona', awayName: 'Newcastle',
    homeColorPrimary: '#A50044', homeColorSecondary: '#004D98',
    awayColorPrimary: '#241F20', awayColorSecondary: '#FFFFFF',
    competition: 'UCL R16 Leg 2', league: 'UCL',
    matchDate: '2026-03-18T18:45:00+00:00',
    status: 'scheduled',
    tier: 'unmissable',
    winProbHome: 65.0, winProbAway: 20.0, winProbDraw: 15.0,
    preview: `Camp Nou. The return. Ninety thousand voices against Eddie Howe's patchwork warriors. If Newcastle arrive here with an advantage from St James' Park — or even level — this becomes one of the great sporting occasions of this decade. Howe's entire project is tested not just tactically but psychologically. Can his squad, depleted of its leaders, play away from home in this cauldron with the belief that they belong?\n\nBarcelona have the home advantage, the quality, the Spotify Camp Nou finishing its renovation into one of European football's great stages. Flick's system does not show mercy to defensive sides — the press, the speed in transition, Yamal on the right cutting inside, Raphinha on the left, Lewandowski leading.\n\nAnd yet. Football has a tendency to produce its most improbable stories in exactly these settings. Newcastle being here at all is already improbable. The question is whether improbable becomes impossible.`,
    refereeName: 'Daniele Orsato',
    refereeNote: 'Same as Leg 1. Tends to protect home side rhythm. Barça will benefit from that understanding.',
    isDerby: false, isPinned: true, weekLabel: 'mar-7-2026',
  },
]

// ── STORIES ───────────────────────────────────────────────────────────────────
export const STORIES_SEED: Story[] = [
  {
    id: 'MUN-mar-7-2026',
    teamId: 'MUN', league: 'EPL', weekLabel: 'mar-7-2026', isActive: true,
    tag: 'YOUR UNITED',
    title: 'The Carrick Awakening',
    druryQuote: 'Once they were the Theatre of Dreams. Then came the years of rust and rubble, of false dawns and broken promises, of managers who arrived with blueprints and left with apologies. But Michael Carrick — who once sat in this dressing room as a player, who knows its ghosts by name — has given Old Trafford something it had not felt in half a decade: the quiet, addictive, dangerous belief that they might actually be building something real.',
    body: `Manchester United sit THIRD in the Premier League with 51 points. That is not a lucky position. It is not a soft section of the table being exploited by a weak calendar. It is the consequence of a defined system, a clear identity, and a coaching staff that has rebuilt the club's relationship with competitive organisation after years of tactical anarchy.\n\nMichael Carrick engineered an eleven-game unbeaten run — a sequence of results that reminded the Premier League that Old Trafford is not a guaranteed three points anymore. That run was ended last week by Newcastle's 2-1 victory. But before we catastrophise: United had been beaten by their opponents in the UCL Round of 16 against Barcelona. Newcastle are not average. The defeat stings, but it does not define.\n\nBenjamin Sesko is the transfer window's silent winner. Signed from RB Leipzig, the Slovenian striker brings directness, intelligent movement, and a capacity to score in big moments that United have been missing since Van Nistelrooy was in his prime. He and Bruno Fernandes — both scored against Crystal Palace in the 2-1 comeback win — have formed a partnership that is efficient rather than spectacular, which is exactly what Carrick wants. Bruno remains the heartbeat: 14 goals, 17 assists, captain class.\n\nInjury watch is the subplot that matters most right now. Lisandro Martínez and Matthijs de Ligt both remain absent. Mason Mount — months away from the pitch — is now 'on the grass' per Carrick's press conference. 'Getting closer.' When Mount plays at 100%, United's midfield is among the best in the division. His return could be the ignition point for the final push into top four.\n\nThe thing nobody is saying enough about: Kobbie Mainoo's form. When he plays at 100%, United's midfield is world-class. When he dithers — as he has in recent weeks — the entire press structure loses its anchor. Carrick has kept faith in him over Manuel Ugarte. That decision is either the manager's greatest confidence call or his most costly gamble. We find out in the next six weeks.\n\nTransfer context: Patrick Dorgu arrived in January and has slotted in at left back. The club is clearly rebuilding with a plan rather than reacting to crises. The days of panic signings in the final hours of a window appear — tentatively — behind them. Harry Maguire's future beyond this summer is the quiet question nobody is asking yet.`,
    statsJson: ['3rd EPL · 51pts · GD +12', 'Fernandes: 14g / 17a', 'Sesko: 9g / 4a', 'Mason Mount: return imminent', 'Unbeaten run: 11 (ended Mar 4)'],
  },
  {
    id: 'BAR-mar-7-2026',
    teamId: 'BAR', league: 'LA_LIGA', weekLabel: 'mar-7-2026', isActive: true,
    tag: 'YOUR BARÇA',
    title: "Flick's Symphony in Blue and Red",
    druryQuote: 'There is a moment in music when an orchestra stops rehearsing and simply plays — when every instrument locks into every other and the sound becomes something larger than its parts. That is FC Barcelona in 2025-26 under Hansi Flick. Not a team of superstars performing in parallel, but a single organism moving with velocity and purpose and joy.',
    body: `Barcelona lead La Liga with 65 points from 27 games. Twenty-one wins. One draw. Four defeats. Under Hansi Flick — who won the Champions League with Bayern Munich in 2020 and built his coaching reputation on precisely this kind of high-press, vertical-transition football — this Barça side has rediscovered what made them feared under Guardiola a decade ago, but now inhabited by a new generation.\n\nLamine Yamal, at 18 years old, is the most exciting player on earth. His dribbling numbers are elite by any metric. His decision-making in tight spaces is not instinct learned from coaching — it appears to be instinct received at birth, refined by however many hours he spent on the streets of Rocafonda before the football world noticed him. Pedri, after a nightmare two-year injury carousel, is the midfield conductor again. Lewandowski at 37 continues to defy reasonable expectation.\n\nAnd then there is Marcus Rashford. The man whom Manchester United supporters watched self-destruct publicly — dropped, form gone, future uncertain — walked into Camp Nou in January and immediately found purpose again. He scored in the UCL league phase against Newcastle. He starts wide left and his direct, pace-based threat gives Barça something they have been missing since Neymar: a wide forward who makes defenders genuinely afraid of what happens if they get the angle wrong.\n\nFrenkie de Jong is the absentee who matters most for the UCL. His injury reduces Barça's midfield range in transitions — he controls rhythm and ball progression in ways Marc Casadó cannot yet replicate. Against Newcastle on Tuesday, this absence is significant. But Flick has options: Gavi returning to form, Dani Olmo's positioning intelligence.\n\nThe thing nobody is saying enough about: Marc Bernal. Just 17. He has come off the bench in several league games and looked, each time, like a senior player who wandered into a youth match. His ball recovery rate in limited minutes is elite-level. Flick has mentioned him privately. Remember the name before the rest of Europe is forced to learn it.\n\nFinancial context: Camp Nou's renovation continues — total cost approaching €1.5 billion. UCL match tickets at the temporary capacity start at €80 for the cheapest seats, a 30% increase from last season. Fan groups have registered displeasure. The club's position: the new stadium revenue justifies everything. We will revisit that conversation when the renovation is complete.`,
    statsJson: ['1st La Liga · 65pts', 'Lewandowski: 23g season', 'Yamal: 12g / 18a', 'Rashford: 4g / 3a since Jan', 'De Jong: absent UCL'],
  },
  {
    id: 'ARS-mar-7-2026',
    teamId: 'ARS', league: 'EPL', weekLabel: 'mar-7-2026', isActive: true,
    tag: 'ARSENAL — QUADRUPLE WATCH',
    title: "Arteta's North London Crusade",
    druryQuote: 'They said Arsenal could not do it. They said the ghost of Wenger\'s invincibles was too heavy to carry, that north London\'s red half was cursed to finish second. But Mikel Arteta — the student who became the professor — has done something genuinely extraordinary. He has made Arsenal boring to play against and thrilling to watch. He has built a team that wins with character as much as quality.',
    body: `Arsenal are FIRST in the Premier League. 67 points. 20 wins. 7 draws. 3 defeats. They are in the Champions League Round of 16 against Bayer Leverkusen with a 62.3% win probability. Depending on FA Cup progression, they remain theoretically alive in three competitions simultaneously.\n\nIf Arsenal win the league, the UCL, and the FA Cup — that is a treble. It has happened once in the Premier League era: Treble United in 1999. Arsenal achieving it would be seismic. It would validate Arteta's project beyond any argument.\n\nThe tactical evolution that is not discussed enough: Arteta has quietly shifted from a 4-3-3 to a 4-2-3-1 in possession and a 4-4-2 in defensive shape. The double pivot of Partey and Rice — or Jorginho when rotation demands — gives Arsenal a compactness that makes them extraordinarily difficult to transition against. Saka and Martinelli invert from the wings. Havertz leads the line but drops to link. The overloads this creates are systematic, not accidental.\n\nKey stat that is not said often enough: Arsenal have the best expected goals against (xGA) in European football this season. They do not just outscore opponents. They systematically prevent opponents from generating quality chances. Their defensive organisation is the least celebrated aspect of Arteta's work and arguably the most important.\n\nGabriel Magalhães has been managing a knock. He is irreplaceable in this system. If he misses the Leverkusen legs, the entire defensive structure requires recalibration. Monitor his training updates this week.\n\nScouting desk: Ethan Nwaneri. Just 17. Started two league games this season when Saka was rested. His technical profile is extraordinary for his age — dribble completion 79%, key passes per 90: 2.1 in limited samples. He is not yet ready for UCL knockout minutes. But he will be next season. The academy pipeline that produced Saka is producing his successor.`,
    statsJson: ['1st EPL · 67pts', 'Saka: 16g / 14a', 'Havertz: 11g', 'Martinelli: 10g / 9a', 'xGA: best in Europe'],
  },
  {
    id: 'UCL-mar-7-2026',
    teamId: 'UCL', league: 'UCL', weekLabel: 'mar-7-2026', isActive: true,
    tag: 'UCL — THE ROUND THAT DECIDES EVERYTHING',
    title: 'Eight Ties. One Budapest Final.',
    druryQuote: 'March. The month when dreamers become believers and believers become champions. The Champions League does not wait for you to be ready. It arrives at your door, turns the handle, and demands an honest answer to the most important question in club football: who are you, really, when everything is at stake?',
    body: `Eight ties. Sixteen clubs. One final in Budapest on May 30. The Champions League Round of 16 is the tournament's most brutal filter — the moment when league form becomes irrelevant and the quality of a squad at its deepest, the composure of a manager at his sharpest, and the fortune of a draw all converge into ninety-minute verdicts.\n\nThe headline fixture is Real Madrid versus Manchester City — the third instalment of a rivalry that has defined European football for three seasons. City won in 2023. Madrid ended their run in 2024. What happens across these two legs will decide which institution goes further and, more importantly, which narrative prevails: Guardiola's total football machine or the Bernabéu's supernatural claim on European football.\n\nBarcelona versus Newcastle is the underdog story the neutral craves. Newcastle — UCL participants only through Eddie Howe's careful construction and the ambitions of their ownership — face the best team in La Liga while missing their best midfielder and four other regulars. Rashford's presence in the Barça squad adds a narrative thread that no screenwriter would dare invent.\n\nArsenal against Leverkusen is the tactical chess match: two high-press teams, two managers who obsess over structure and data, playing a game that could determine Arsenal's historic season. Arsenal's 62.3% win probability is the most emphatic favourite's position in this round.\n\nThe dark horse nobody is saying enough about: Monaco. They beat PSG 3-1 in Ligue 1 this week at the Parc des Princes — their most impressive performance of the season. They pushed PSG in the UCL play-offs. Adi Hütter has built something quietly excellent. If they qualify for the quarter-finals this spring, everyone will pretend they saw it coming. They did not.`,
    statsJson: ['UCL Final: Budapest, May 30', 'QF: Apr 7-8 & 14-15', 'SF: Apr 28-29 & May 5-6', 'City/Madrid: Third act', 'Arsenal: 62.3% vs Leverkusen'],
  },
  {
    id: 'NEW-mar-7-2026',
    teamId: 'NEW', league: 'EPL', weekLabel: 'mar-7-2026', isActive: true,
    tag: 'NEWCASTLE — THE UNDERDOG STORY',
    title: 'The Magpies in Europe',
    druryQuote: 'Some clubs carry history like a crown. Others carry it like a wound. Newcastle United, for so long, wore theirs as the latter — the great northern club that almost was, the stadium that deserved more than the table offered. Now, under floodlights, in the Champions League, they carry it differently.',
    body: `Newcastle United are in the Champions League Round of 16. Let that sentence breathe for a moment. In the history of this competition in its current format, the number of times a club of Newcastle's recent trajectory — ownership change, financial fair play navigation, squad construction under FFP constraints — has reached this stage is vanishingly small.\n\nEddie Howe has done it without Bruno Guimarães. Without Fabian Schär. Without Lewis Miley, Tino Livramento, and Emil Krafth. His team beat Qarabag 6-1 away from home in the preliminary round to qualify for the knockout stage. They deserve their night under the lights at St James' Park against Barcelona.\n\nIn the Premier League they sit twelfth on 39 points — a position that reflects the injury crisis rather than the squad's ceiling. When fit, this is a top-six team. With Guimarães in midfield, the control and tempo they generate is Premier League-quality and then some.\n\nScouting note that is being criminally overlooked: Anthony Gordon. When Gordon is at his best — direct, aggressive, two-footed threat from wide positions — he is as good as anything in the Premier League. His recent form has been quietly excellent. Watch him against Barcelona's back line on Tuesday. He may be the player who changes the tie.`,
    statsJson: ['12th EPL · 39pts', 'UCL R16 vs Barcelona', 'Guimarães: absent (injury)', 'Gordon: form player', 'Howe: 3rd UCL qualification'],
  },
  {
    id: 'MCI-mar-7-2026',
    teamId: 'MCI', league: 'EPL', weekLabel: 'mar-7-2026', isActive: true,
    tag: 'MAN CITY — THE MACHINE',
    title: "Haaland's European Mission",
    druryQuote: 'Pep Guardiola has built many things in football. He has built tiki-taka. He has built gegenpressing. He has built the most dominant league team in English history. But he has not built a second Champions League since 2023, and that absence — for a man who treats mediocrity as a personal insult — defines this season more than any other variable.',
    body: `Manchester City are second in the Premier League with 60 points — seven behind Arsenal, two ahead of United. Their league campaign has been excellent without being dominant, which is itself a form of relative underperformance when you consider the squad Guardiola has assembled.\n\nErling Haaland is the most feared striker alive. His numbers are, by now, almost boring to enumerate: goals at a rate that makes even the most cynical statistician blink. His partnership with Kevin De Bruyne — when De Bruyne is fit — gives City a combination that no back line in European football has solved for ninety minutes when both are operating at their ceiling.\n\nThe Bernabéu this Wednesday is the focal point of City's entire season. They were eliminated there in 2024. They know what the stadium does to teams. They know what Ancelotti does with a lead. The question is whether this City side, at this moment, has the collective nerve to go to Madrid and play their football under the most hostile possible conditions.\n\nTactical note: Guardiola has been experimenting with a higher defensive line this season — riskier against transitions, but more compact in possession. Against Haaland-less opposition, it works perfectly. Against Real Madrid's wide players, it will be tested at every opportunity.\n\nScouting desk: Oscar Bobb. Norwegian. 22. Has been excellent when given minutes. His technical quality and direct running give City an option that doesn't replicate what they already have — he's a creator rather than a finisher. Guardiola rates him highly in training.`,
    statsJson: ['2nd EPL · 60pts', 'Haaland: 28g season', 'De Bruyne: 8g / 14a', 'UCL vs Real Madrid', 'City: 47% win prob at Bernabéu'],
  },
  {
    id: 'LFC-mar-7-2026',
    teamId: 'LFC', league: 'EPL', weekLabel: 'mar-7-2026', isActive: true,
    tag: 'LIVERPOOL — THE PURSUIT',
    title: "Slot's High-Wire Act",
    druryQuote: 'Arne Slot arrived at Anfield with the impossible task of not being Jürgen Klopp. He has managed something more difficult: he has been entirely himself. And Liverpool, six months into understanding what that means, are beginning to look like themselves again.',
    body: `Liverpool sit sixth in the Premier League with 48 points — level on points with Chelsea but behind on goal difference. In the context of Arsenal's runaway lead, that is a battle for European qualification rather than a title race. But sixth place in this squad's currency is not failure. It is a re-calibration year under a manager who spent his first season at one of the world's most scrutinised clubs without producing a single week of genuine discomfort about the transition.\n\nMohamed Salah is in the final year of his contract. The summer window will define whether he becomes the player who stayed and won a league title under Slot, or the player who left when Anfield didn't provide the terms he required. His form this season has been what his form always is: extraordinary. 18 goals, 11 assists. The Egyptian King has not declined. The negotiations will be watched closely.\n\nDarwin Núñez remains Liverpool's most divisive figure — and their most electric in transition. His xG underperformance is still significant: he creates space that other strikers cannot create, but the finishing has not yet matched the movement. Slot has been patient. The goals are coming — 12 this season, his best tally in England.\n\nTactical evolution: Slot has introduced a more structured midfield pressing structure than Klopp's. Liverpool under Klopp pressed with emotional intensity. Under Slot, it is positional. More planned, less frenetic. Alexis Mac Allister has been the principal beneficiary — his ball-winning in midfield is elite under this system.\n\nThe UCL exit in the quarter-finals last season — against Galatasaray, of all opponents — was the wound that galvanised this week's fixture. Galatasaray at the Türk Telekom Stadium is a hostile environment. Liverpool travel with a 58% win probability. But this competition does not reward probability alone.\n\nScouting desk: Harvey Elliott. 21. Missed significant time to injury. When he returns, watch him at right midfielder in Slot's system. His spatial awareness and combination play are exceptional — the kind of player who, at 23, will be regarded as Liverpool's best midfield option. He is not far away.`,
    statsJson: ['6th EPL · 48pts', 'Salah: 18g / 11a', 'Núñez: 12g season', 'UCL vs Galatasaray', 'Salah contract: summer decision'],
  },
  {
    id: 'CFC-mar-7-2026',
    teamId: 'CFC', league: 'EPL', weekLabel: 'mar-7-2026', isActive: true,
    tag: 'CHELSEA — RISING',
    title: "Palmer's European Moment",
    druryQuote: 'Cole Palmer arrived at Chelsea as the question nobody could answer with confidence. He has become the answer to every question they had. In a squad assembled with more money than any other in football history, the most important player is the one who cost £42 million from Manchester City — a fee that already looks like an administrative error on City\'s part.',
    body: `Chelsea sit fifth in the Premier League with 48 points, level with Liverpool, one place above on goal difference. For a club that spent in excess of £900 million across three transfer windows, fifth is not the destination the ownership envisioned. But the coaching carousel has ended. Enzo Maresca is the first Chelsea manager since Conte who has been given more than seven months to build an identity.\n\nAnd the identity is becoming visible. Chelsea are beginning to look like a defined football team rather than a collection of expensive individuals processing in parallel. The 4-1 win against Aston Villa three weeks ago — Palmer's two goals, Pedro Neto's brilliant opener, the tactical control in the second half — is the template for what this squad can produce when everything aligns.\n\nIn the UCL they face PSG at the Parc des Princes on Tuesday. PSG — who just lost 3-1 to Monaco in Ligue 1 — are vulnerable in ways they rarely have been. Their squad, rebuilt without Mbappé, does not have the same psychological certainty. Chelsea's win probability is 38%, the outsider's price. But this is a team that ended City's UCL campaign last season from a similar position.\n\nNicolas Jackson's finishing is still the conversation. His xG overperformance in September — three goals from 1.8 xG across three games — was the inflection point. His underperformance in December lost Chelsea three points. He remains the player who decides Chelsea's ceiling.\n\nScouting desk: Renato Veiga. Portuguese. 21. Centre-back with elite passing range for a defender. His ball-playing from the back in Maresca's system gives Chelsea an extra creation option. There is a version of Chelsea where Veiga is one of the best defenders in Europe within three seasons. The foundations are visible.`,
    statsJson: ['5th EPL · 48pts', 'Palmer: 14g / 13a', 'Jackson: 12g season', 'UCL vs PSG', '4-1 vs Villa: statement result'],
  },
  {
    id: 'PSG-mar-7-2026',
    teamId: 'PSG', league: 'LIGUE_1', weekLabel: 'mar-7-2026', isActive: true,
    tag: 'PSG — THE POST-MBAPPÉ REINVENTION',
    title: 'Kvaratskhelia and the New Chapter',
    druryQuote: 'When Kylian Mbappé left for Real Madrid, the conversation in Paris was grief. The club mourned a once-in-a-generation talent the way a city mourns an era. But football does not grieve. Football replaces. And the replacement — not of Mbappé\'s speed, but of the purpose that speed served — is something PSG is still assembling in real time.',
    body: `PSG sit second in Ligue 1 with 57 points, three behind Marseille. Three points behind. That sentence would have been considered crisis-level in the Mbappé era. Under Luis Enrique, it is a recalibration — a coaching project that places collective movement above individual expression, a philosophy that has turned the squad into something more functional and something less thrilling.\n\nKhvicha Kvaratskhelia arrived from Napoli in January and has already changed the attack's character. His direct, physical dribbling from the left offers PSG something they lacked: an opponent who does not know which direction he is going next. He is not Mbappé — nobody is — but he is a genuinely elite wide forward who causes panic in defenders at the highest level.\n\nThe 3-1 loss to Monaco at home last weekend is the latest chapter in PSG's Ligue 1 anxiety. Luis Enrique rotated with the UCL in mind — Chelsea on Tuesday looms large — but the result was 3-1 and the response from the Parc des Princes was not patient. The relationship between the club's ownership expectations and the coach's patient construction is a permanent tension.\n\nUCL perspective: PSG have won the UCL zero times. For a club with the resources they possess, that remains the most persistent criticism of their project. Chelsea on Tuesday is not the final — but against a side coming from England with momentum and a manager who knows Maresca's system, it is far from straightforward.\n\nScouting desk: Yoram Zague. 17. Brazilian. Has come off the bench twice in Ligue 1. His movement in tight spaces is extraordinary for his age. Luis Enrique has mentioned him in press conferences twice. Watch him when he gets minutes — they are coming.`,
    statsJson: ['2nd Ligue 1 · 57pts', 'Kvaratskhelia: 6g / 4a since Jan', 'UCL vs Chelsea', 'Monaco loss: 3-1 home', 'Mbappé era: truly over'],
  },
  {
    id: 'BMU-mar-7-2026',
    teamId: 'BMU', league: 'BUNDESLIGA', weekLabel: 'mar-7-2026', isActive: true,
    tag: 'BAYERN — KANE\'S CRUSADE',
    title: "The Redemption Arc Continues",
    druryQuote: 'Harry Kane came to Munich to win the things England never gave him. A league title. A Champions League. The things that define a footballer\'s career beyond the goals. He arrived with scepticism trailing him: a centre-forward in the Bundesliga\'s most dominant machine, expected to perform and not to define. He has, quietly and without fanfare, redefined everything.',
    body: `Bayern Munich lead the Bundesliga by eight points. They have not been this dominant in the German top flight since the quadruple-winning era of Lewandowski and Müller. Vincent Kompany — the choice that surprised many when appointed — has evolved from a question mark into a statement. His high-pressing, vertical system suits Kane in ways that Tuchel's rigid structure never fully exploited.\n\nHarry Kane has 29 goals in all competitions. 22 in the Bundesliga. This is the most complete season of his career — not the most individual, but the most collective. He is linking play better than before, pressing more intelligently, and converting the difficult chances that great strikers turn into routine. He is the Bundesliga's top scorer by six goals.\n\nThe UCL fixture against Atalanta is the test of a different kind. Gian Piero Gasperini has spent fifteen years making elite opponents question themselves. His 3-4-3 disrupts space in ways that 4-3-3 systems struggle to handle. Bayern's width — Leroy Sané and Kingsley Coman at their best — should be the advantage. But Atalanta's press has caught bigger sides.\n\nJoshua Kimmich at right back remains the most underappreciated deployment in European football. His positioning intelligence turns defence into attack at a speed that consistently catches opponents. He is arguably the best right back in the world when assessed on output alone.\n\nScouting desk: Aleksandar Pavlović. 20. Defensive midfielder. Has had a breakout Bundesliga campaign when fit. His reading of space in Bayern's press is exceptional. Kompany uses him as the pivot that holds the structure together. He is why Bayern's press does not collapse when Kimmich ventures forward.`,
    statsJson: ['1st Bundesliga · gap: 8pts', 'Kane: 29g all comps', 'UCL vs Atalanta', 'Kompany: 2nd season clarity', 'Kimmich: best RB in Europe'],
  },
  {
    id: 'DERBY-mar-7-2026',
    teamId: 'ACM', league: 'SERIE_A', weekLabel: 'mar-7-2026', isActive: true,
    tag: 'DERBY DELLA MADONNINA',
    title: 'Milan Against Milan — The Derby That Defines the City',
    druryQuote: 'In a city that has two cathedrals — one of stone, one of football — there are two clubs, two identities, two versions of what Milanese football should be. For ninety minutes, all other conversations stop. The Derby della Madonnina is not a match. It is a referendum.',
    body: `The Derby della Madonnina. Inter versus AC Milan. The fixture that divides a city not by geography — both clubs share the Giuseppe Meazza stadium, which is itself a statement — but by philosophy, history, and the specific kind of inherited identity that Italian football carries more ferociously than any other culture.\n\nInter Milan are second in Serie A, four points behind Napoli. Simone Inzaghi has built the most tactically coherent Inter side since the Mourinho treble team of 2010 — not as physical, but more intelligent in possession and more systematic in their pressing triggers. Lautaro Martínez is the best centre-forward in Italy. Marcus Thuram is the ideal partner — different profile, constant problem.\n\nAC Milan are fifth, seven points back. Paulo Fonseca was sacked in November after three consecutive draws. His replacement — Sérgio Conceição, the Porto manager who turned European underdog stories into knockout stage reality — has won six of his nine games in charge. Milan are moving. The tactical shift from Fonseca's patient buildup to Conceição's direct vertical pressing has been visible and effective.\n\nThe derby decides European positioning for both clubs. Inter need a win to maintain pressure on Napoli. Milan need three points to keep their Europa League qualification alive. When European stakes meet local pride, something extraordinary tends to emerge.\n\nTactical detail worth noting: Inter's offside trap is the most aggressive in Serie A. Milan's wide forwards — Rafael Leão and Samuel Chukwueze — are the fastest in the league in transition. The tactical battle between Inter's offside line and Milan's speed on the break will determine the contest more than any individual duel.\n\nScouting desk: Francesco Camarda at AC Milan. 17 years old. Already scored in Serie A as the youngest debut scorer in the competition's history. Conceição has kept faith in him as a rotation option. He is exceptional.`,
    statsJson: ['2nd Serie A · Inter · 4pts off top', '5th Serie A · Milan · 7pts off top', 'Lautaro: 17g season', 'Leão: 9g / 11a', 'Conceição: 6W from 9'],
  },
]

// ── PLAYER STATS ──────────────────────────────────────────────────────────────
export const PLAYER_STATS_SEED: PlayerStat[] = [
  // Manchester United
  { teamId:'MUN', playerName:'Bruno Fernandes',   position:'MID', goals:14, assists:17, xg:10.2, chancesCreated:67, ballRetentionPct:88.2, minutesPlayed:2340, appearances:27, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'MUN', playerName:'Benjamin Sesko',    position:'FWD', goals:9,  assists:4,  xg:9.8,  chancesCreated:24, ballRetentionPct:72.1, minutesPlayed:1980, appearances:24, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'MUN', playerName:'Bryan Mbeumo',      position:'FWD', goals:7,  assists:8,  xg:6.4,  chancesCreated:41, ballRetentionPct:78.4, minutesPlayed:2100, appearances:26, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'MUN', playerName:'Matheus Cunha',     position:'FWD', goals:6,  assists:7,  xg:5.9,  chancesCreated:38, ballRetentionPct:76.2, minutesPlayed:1870, appearances:24, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'MUN', playerName:'Kobbie Mainoo',     position:'MID', goals:3,  assists:5,  xg:2.8,  chancesCreated:29, ballRetentionPct:91.4, minutesPlayed:2200, appearances:26, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'MUN', playerName:'Mason Mount',       position:'MID', goals:2,  assists:3,  xg:2.1,  chancesCreated:18, ballRetentionPct:87.0, minutesPlayed:680,  appearances:9,  isInjured:true,  injuryNote:'Muscle issue — return imminent per Carrick', statWeek:'mar-7-2026' },
  { teamId:'MUN', playerName:'Leny Yoro',         position:'DEF', goals:0,  assists:1,  xg:0.4,  chancesCreated:5,  ballRetentionPct:93.1, minutesPlayed:1440, appearances:17, isInjured:false, scoutingNote:'19yo CB — composed in possession, exceptional reading of play. Future United captain material.', statWeek:'mar-7-2026' },
  // Barcelona
  { teamId:'BAR', playerName:'Robert Lewandowski', position:'FWD', goals:23, assists:6,  xg:20.1, chancesCreated:28, ballRetentionPct:74.2, minutesPlayed:2280, appearances:27, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'BAR', playerName:'Lamine Yamal',       position:'FWD', goals:12, assists:18, xg:9.8,  chancesCreated:91, ballRetentionPct:82.4, minutesPlayed:2310, appearances:27, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'BAR', playerName:'Raphinha',           position:'FWD', goals:11, assists:9,  xg:10.4, chancesCreated:64, ballRetentionPct:80.1, minutesPlayed:2140, appearances:26, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'BAR', playerName:'Marcus Rashford',    position:'FWD', goals:4,  assists:3,  xg:4.1,  chancesCreated:22, ballRetentionPct:76.8, minutesPlayed:980,  appearances:14, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'BAR', playerName:'Pedri',              position:'MID', goals:4,  assists:11, xg:3.2,  chancesCreated:72, ballRetentionPct:92.3, minutesPlayed:2020, appearances:25, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'BAR', playerName:'Frenkie de Jong',    position:'MID', goals:1,  assists:5,  xg:1.4,  chancesCreated:31, ballRetentionPct:93.8, minutesPlayed:1340, appearances:18, isInjured:true,  injuryNote:'Muscle injury — out UCL vs Newcastle', statWeek:'mar-7-2026' },
  { teamId:'BAR', playerName:'Marc Bernal',        position:'MID', goals:0,  assists:1,  xg:0.6,  chancesCreated:9,  ballRetentionPct:88.9, minutesPlayed:380,  appearances:8,  isInjured:false, scoutingNote:'17yo. Elite ball recovery rate in limited minutes. Flick rates him highly. Next great La Masia product.', statWeek:'mar-7-2026' },
  // Arsenal
  { teamId:'ARS', playerName:'Bukayo Saka',        position:'FWD', goals:16, assists:14, xg:13.2, chancesCreated:88, ballRetentionPct:81.4, minutesPlayed:2280, appearances:27, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'ARS', playerName:'Kai Havertz',        position:'FWD', goals:11, assists:7,  xg:10.8, chancesCreated:41, ballRetentionPct:78.2, minutesPlayed:2200, appearances:27, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'ARS', playerName:'Gabriel Martinelli',  position:'FWD', goals:10, assists:9,  xg:9.4,  chancesCreated:59, ballRetentionPct:77.6, minutesPlayed:2060, appearances:26, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'ARS', playerName:'Martin Ødegaard',    position:'MID', goals:7,  assists:12, xg:6.2,  chancesCreated:79, ballRetentionPct:90.4, minutesPlayed:2180, appearances:26, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'ARS', playerName:'Declan Rice',        position:'MID', goals:4,  assists:6,  xg:3.8,  chancesCreated:44, ballRetentionPct:92.1, minutesPlayed:2300, appearances:27, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'ARS', playerName:'Ethan Nwaneri',      position:'MID', goals:1,  assists:2,  xg:1.1,  chancesCreated:14, ballRetentionPct:84.2, minutesPlayed:420,  appearances:9,  isInjured:false, scoutingNote:'17yo. Saka\'s heir apparent. 79% dribble completion. 2.1 key passes/90 in limited sample. Next season is his.', statWeek:'mar-7-2026' },
  // Newcastle
  { teamId:'NEW', playerName:'Alexander Isak',     position:'FWD', goals:14, assists:5,  xg:12.8, chancesCreated:31, ballRetentionPct:73.4, minutesPlayed:1980, appearances:24, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'NEW', playerName:'Anthony Gordon',     position:'FWD', goals:8,  assists:9,  xg:7.2,  chancesCreated:56, ballRetentionPct:79.1, minutesPlayed:2120, appearances:26, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'NEW', playerName:'Bruno Guimarães',    position:'MID', goals:4,  assists:8,  xg:3.6,  chancesCreated:48, ballRetentionPct:91.8, minutesPlayed:1620, appearances:20, isInjured:true,  injuryNote:'Absent UCL vs Barcelona — return date unclear', statWeek:'mar-7-2026' },
  { teamId:'NEW', playerName:'Jacob Murphy',       position:'FWD', goals:5,  assists:6,  xg:4.4,  chancesCreated:32, ballRetentionPct:76.2, minutesPlayed:1440, appearances:22, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'NEW', playerName:'Joelinton',          position:'MID', goals:3,  assists:4,  xg:2.9,  chancesCreated:24, ballRetentionPct:82.6, minutesPlayed:1860, appearances:24, isInjured:false, statWeek:'mar-7-2026' },
  // Chelsea
  { teamId:'CFC', playerName:'Cole Palmer',        position:'MID', goals:14, assists:13, xg:11.8, chancesCreated:84, ballRetentionPct:86.4, minutesPlayed:2260, appearances:27, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'CFC', playerName:'Nicolas Jackson',    position:'FWD', goals:12, assists:5,  xg:13.2, chancesCreated:29, ballRetentionPct:71.4, minutesPlayed:2040, appearances:26, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'CFC', playerName:'Pedro Neto',         position:'FWD', goals:7,  assists:10, xg:6.4,  chancesCreated:62, ballRetentionPct:78.8, minutesPlayed:1880, appearances:24, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'CFC', playerName:'Enzo Fernández',     position:'MID', goals:4,  assists:8,  xg:3.2,  chancesCreated:51, ballRetentionPct:88.4, minutesPlayed:2100, appearances:26, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'CFC', playerName:'Moisés Caicedo',     position:'MID', goals:2,  assists:4,  xg:2.0,  chancesCreated:33, ballRetentionPct:91.2, minutesPlayed:2180, appearances:27, isInjured:false, statWeek:'mar-7-2026' },
  // Liverpool
  { teamId:'LFC', playerName:'Mohamed Salah',      position:'FWD', goals:18, assists:11, xg:15.4, chancesCreated:71, ballRetentionPct:80.2, minutesPlayed:2280, appearances:27, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'LFC', playerName:'Darwin Núñez',       position:'FWD', goals:12, assists:5,  xg:14.1, chancesCreated:28, ballRetentionPct:71.8, minutesPlayed:1980, appearances:24, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'LFC', playerName:'Luis Díaz',          position:'FWD', goals:9,  assists:8,  xg:8.6,  chancesCreated:54, ballRetentionPct:77.4, minutesPlayed:2040, appearances:25, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'LFC', playerName:'Alexis Mac Allister', position:'MID', goals:5,  assists:9,  xg:4.2,  chancesCreated:62, ballRetentionPct:89.4, minutesPlayed:2220, appearances:27, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'LFC', playerName:'Dominik Szoboszlai',  position:'MID', goals:6,  assists:6,  xg:5.1,  chancesCreated:48, ballRetentionPct:84.6, minutesPlayed:1980, appearances:25, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'LFC', playerName:'Harvey Elliott',     position:'MID', goals:2,  assists:3,  xg:1.8,  chancesCreated:22, ballRetentionPct:83.2, minutesPlayed:620,  appearances:11, isInjured:false, scoutingNote:'21yo. Spatial awareness and combination play elite for his age. Slot\'s system unlocks his best — future Liverpool #10 candidate.', statWeek:'mar-7-2026' },
  // Man City
  { teamId:'MCI', playerName:'Erling Haaland',     position:'FWD', goals:28, assists:4,  xg:25.4, chancesCreated:18, ballRetentionPct:68.2, minutesPlayed:2200, appearances:26, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'MCI', playerName:'Kevin De Bruyne',    position:'MID', goals:8,  assists:14, xg:6.8,  chancesCreated:88, ballRetentionPct:89.6, minutesPlayed:1840, appearances:22, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'MCI', playerName:'Phil Foden',         position:'MID', goals:10, assists:8,  xg:9.2,  chancesCreated:61, ballRetentionPct:84.4, minutesPlayed:2000, appearances:25, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'MCI', playerName:'Bernardo Silva',     position:'MID', goals:6,  assists:9,  xg:5.4,  chancesCreated:54, ballRetentionPct:91.8, minutesPlayed:1980, appearances:26, isInjured:false, statWeek:'mar-7-2026' },
  { teamId:'MCI', playerName:'Oscar Bobb',         position:'FWD', goals:4,  assists:5,  xg:3.8,  chancesCreated:28, ballRetentionPct:78.4, minutesPlayed:860,  appearances:14, isInjured:false, scoutingNote:'22yo Norwegian. Direct, two-footed creator. Guardiola rates him highly in training. Future starter.', statWeek:'mar-7-2026' },
]

// ── WEEKLY DIGEST ─────────────────────────────────────────────────────────────
export const WEEKLY_DIGEST_SEED: WeeklyDigest = {
  weekLabel: 'mar-7-2026',
  wildcardTeamId: 'ASM',
  wildcardReason: "Monaco beat PSG 3-1 at the Parc des Princes this week — their best result of the season and a genuine statement of intent. Adi Hütter has built a quietly exceptional side that operates under the radar while the Ligue 1 spotlight follows PSG everywhere else. Takumi Minamino and Breel Embolo are in the form of their careers. Monaco pushed PSG in the UCL play-offs this season. Before the end of this campaign, they will cause a result that makes every outlet that ignored them scramble for context.",
  historyFacts: [
    { date: 'Mar 7', fact: "On this day in 1987, Diego Maradona scored a hat-trick for Napoli against Juventus in a 3-1 win that proved pivotal in their first-ever Serie A title. The Juventus end went conspicuously quiet for the rest of the afternoon." },
    { date: 'Mar 10', fact: "The very first UEFA Champions League match was played on September 25, 1992 — replacing the old European Cup. The competition was designed to be football's ultimate test. Thirty-four years later, Newcastle vs Barcelona at St James' Park is proof it still is." },
    { date: 'Mar 11', fact: "On March 11, 2009, Cristiano Ronaldo struck a free kick against Porto from 40 yards that left Manuel Neuer — then Porto's goalkeeper — frozen. 'And Ronaldo — MAGNIFICENT!' Peter Drury called it. That call still gives chills." },
  ],
  humorItems: [
    "PSG lost 3-1 to Monaco at home in Ligue 1. The Parc des Princes immediately appointed an emergency Director of Vibes. The previous three Directors of Vibes were unavailable for comment.",
    "Real Madrid lost to Getafe at the Bernabéu. Getafe. The stadium briefly renamed itself the Theatre of Surprised Faces. Carlo Ancelotti was photographed staring at the ceiling for forty uninterrupted seconds before anyone dared speak to him.",
    "Bodø/Glimt beat Inter Milan in the UCL aggregate. A club from a Norwegian city where the sun doesn't set in summer eliminated the Italian giants. Inter's sporting director was reportedly photographed Googling 'Where is Bodø' at 11pm local time.",
    "Bruno Fernandes has now scored or assisted in eight consecutive Manchester United appearances. The transfer forums that demanded his sale in 2023 have gone conspicuously quiet. Their silence is its own kind of noise.",
    "Spurs are 16th in the Premier League. They are also in the UCL Round of 16. These two facts coexist peacefully, like two very different paintings hanging in the same confused gallery.",
    "Bayern Munich beat Gladbach 4-1. German media described it as 'workmanlike.' Workmanlike. Harry Kane scored twice. The bar for Bayern has become so high that goals are considered infrastructure.",
  ],
  pinnedFixtures: [
    { label: '🔥 Newcastle vs Barcelona — UCL R16 L1', date: 'Tue Mar 10 · 23:00 EAT', color: '#A50044' },
    { label: '⚔️ Real Madrid vs Man City — UCL R16 L1', date: 'Wed Mar 11 · 23:00 EAT', color: '#FEBE10' },
    { label: '🔴 Man Utd vs Aston Villa — EPL', date: 'Sun Mar 15 · 17:00 EAT', color: '#DA291C' },
    { label: '🏆 Barça vs Newcastle — UCL R16 L2', date: 'Wed Mar 18 · 21:45 EAT', color: '#004D98' },
    { label: '🏟️ UCL FINAL — Budapest', date: 'Sat May 30, 2026', color: '#F5C842' },
  ],
}
